opportunity-hack/backend-ohack.dev

- .gitignore
- api/__init__.py
- api/newsletters/newsletter_views.py
- api/newsletters/smtp.py
- common/utils/__init__.py
- requirements.txt
Fixes import error during start
N/A
> Fix for import errors #9 on start

- api/messages/messages_service.py
- api/messages/messages_views.py
Back-merging (not a best practice) from main to develop
> added previous hackathon capability

- api/messages/messages_service.py
> Description and User json update

- api/messages/messages_service.py
- common/utils/cdn.py
- common/utils/firebase.py
- scripts/util.py
> Getting set for October OHack

- api/messages/messages_service.py
- common/utils/firebase.py
- common/utils/github.py
- common/utils/slack.py
- requirements.txt
> Updatees to support repo creation

- api/messages/messages_service.py
> Not sure why there is a nonetype

- api/messages/messages_service.py
> Logging and rate limiting

- api/messages/messages_service.py
- common/utils/github.py
> Add githubUsername as provided in new team creation dialog

- common/utils/firebase.py
> Add mentoring and judging hearts

- api/messages/messages_service.py
> Small perf improvements

- api/messages/messages_service.py
- api/messages/messages_views.py
- common/utils/firebase.py
- common/utils/openai.py
> Added news

- api/messages/messages_service.py
- api/messages/messages_views.py
> Fix for limit

- api/__init__.py
- api/messages/messages_service.py
Handle moving to Vercel for performance
> Handle moving to Vercel for performance

- api/messages/messages_service.py
- common/utils/openai_api.py
> Added project ranking to only show most important projects

- api/messages/messages_service.py
- api/messages/messages_views.py
- requirements.txt
> Get leads - Startup 101

- .vscode/settings.json
- common/utils/openai_api.py
- scripts/util.py
> New AI image prompt

- api/certificates/certificate_service.py
- api/certificates/certificate_views.py
- common/utils/firebase.py
> #7 Cert index

- api/messages/messages_service.py
- api/messages/messages_views.py
> Add ability to save profile metadata via POST

- api/__init__.py
- api/messages/messages_service.py
> Add the why to profile

- api/__init__.py
- api/messages/messages_service.py
- api/messages/messages_views.py
Fixed profile page. Put back old /api/messages routes until we can cut over to entity specific routes.
Fixes the population of the profile page and self-service profile update.
Related Issue: #58
> Fixed profile page. Put back old /api/messages routes until we can cut over to entity specific routes.

- .gitignore
- api/__init__.py
- api/hearts/hearts_views.py
- model/user.py
- services/hearts_service.py
Adding hearts endpoint to make it easier to administer and show hearts to all the peeps!
> Hearts API Endpoint

- services/hearts_service.py
> To #general we go!

- api/messages/messages_service.py
- fly.toml
- requirements.txt
We were never actually sending emails to people who were signing up for the newsletter, but now we are!
> Newsletter signup, now with 100% more actual email confirmations!

- api/messages/messages_views.py
> easier to send orgId for both test and prod

- api/hearts/hearts_views.py
> Lock down POSTing for heart admin

- api/__init__.py
> bug: prod-specific setting for new header

- api/messages/messages_service.py
Forgot to add the right method params :'(
> Forgot to add the right method params :'(

- api/messages/messages_service.py
- api/users/users_views.py
- model/user.py
- services/users_service.py
> Time tracking 

- api/messages/messages_service.py
- api/messages/messages_views.py
- scripts/990_finder.py
> Volunteer Edit!

- api/messages/messages_service.py
- api/messages/messages_views.py
> Bulk add volunteers

- api/__init__.py
[README] Trying out some new backend monitoring from README as one of our Sponsors of OHack 2024
Now we get some monitoring for our backend
> [README] OHack Sponsor for 2024

- requirements.txt
> reqs for README

- api/messages/messages_service.py
- api/messages/messages_views.py
- common/exceptions.py
- common/utils/validators.py
Needed a way to add and edit nonprofits with new admin UI
> [Admin] Add and Edit nonprofit

- api/messages/messages_service.py
> Handle null better

- .vscode/settings.json
- api/messages/messages_service.py
- api/users/users_views.py
- services/users_service.py
> /volunteer/track - update to show committeed and active time tracking

- api/problemstatements/problem_statement_views.py
- db/firestore.py
- model/donation.py
- model/hackathon.py
- model/problem_statement.py
- services/problem_statements_service.py
Moved over some Problem Statement API calls to the new way of doing this, might break things
> Support of adding videos to problem statements and displaying them

- api/users/users_views.py
- services/users_service.py
> [Admin][Volunteer Tracking] Get all volunteer hours tracked

- api/messages/messages_service.py
- common/utils/slack.py
Updates the timestamp to contain format of **"YYYY-MM-DDTHH:MM:SS-HH:MM"** to account for timezone in US/AZ timezone.
> Updating Timezone Format of Praise Data

- api/leaderboard/leaderboard_service.py
> Remove hardcoded 2024

- api/messages/messages_service.py
- api/messages/messages_views.py
> Add npo to hackathon

- api/__init__.py
- api/messages/messages_service.py
- api/slack/__init__.py
- api/slack/slack_service.py
- api/slack/slack_views.py
- api/slack/tests/test_slack_service.py
- common/utils/slack.py
> [ClaudeCode] Edit NPO admin + Slack user lookup

- api/slack/slack_service.py
> [slack] lower cache since people will be registering during hackathon

- api/teams/teams_service.py
- services/problem_statements_service.py
> Small bugfixes

- api/messages/messages_service.py
- api/messages/messages_views.py
- common/utils/cdn.py
> [ClaudeCode] CDN upload API

- api/messages/messages_service.py
- services/volunteers_service.py
> Sorting Hackathons and sending calendar invites 

- api/messages/messages_service.py
- api/messages/messages_views.py
- api/problemstatements/problem_statement_views.py
- db/firestore.py
- services/problem_statements_service.py
> bugfixes for linking problem statements

- api/teams/teams_service.py
- api/validate/validate_service.py
- services/users_service.py
> Fix backend team creation for a team member that has not signed in

- api/messages/messages_service.py
Enhanced the **/onboarding_feedback** API to update feedback data already submitted by a user of a **known email address AND first name** or **unknown user of a particular user agent and ip address**. 
Backend expects to receive API request in any of the follow format below:
For unknown user:
`{
"overallRating": int,
"usefulTopics": array_of_string,
"missingTopics": string,
"easeOfUnderstanding": string,
"improvements": string,
"additionalFeedback": string,
"contactForFollowup": {
"willing": false
},
"clientInfo": {
"userAgent": string_id,
"ipAddress": string_ip_address
}
}`
For users with known email and first name:
`{
"overallRating": int,
"usefulTopics": array_of_string,
"missingTopics": string,
"easeOfUnderstanding": string,
"improvements": string,
"additionalFeedback": string, …
> Update onbaording feedback existing in database
